Upload csv inner control
IGinX-THU/zeppelin-interpreter pull request #13
Opened 2024-10-15 09:17 UTC by liuxtq

2024-10-16 09:36 UTC, Yihao-Xu requested changes

2024-10-16 09:36 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +  private static final String DEFAULT_FILE_UPLOAD_DIR = "/opt/module/zeppelin/uploads";
这里仿照上面的`DEFAULT_OUTFILE_DIR`改成类似的吧，让用户自己配置

2024-10-16 09:36 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +  private static final String DEFAULT_FILE_UPLOAD_DIR = "/opt/module/zeppelin/uploads";
这个UPLOAD DIR要实现成用户可配置的，参考resource里的interpreter-setting.json
包括下面的upload max size也是

2024-10-16 09:36 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +  private static final String DEFAULT_FILE_UPLOAD_DIR = "/opt/module/zeppelin/uploads";
具体从配置的读取参考open函数

2024-10-16 09:36 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +              + " It needs to be less than 10GB, but the actual upload size was "
这里10GB改成可配置的，不要写死

2024-10-16 09:36 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/SimpleFileServer.java
> +    private static final long UPLOAD_FILE_DIR_MAX_SIZE = 200L * 1024 * 1024 * 1024; // 100GB
这个也调整成可配置的吧

2024-10-16 09:36 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/SimpleFileServer.java
> +                    "%s:18080/api/notebook/run/%s/%s", zeppelinUrl, noteBookId, paragraphId),
这里端口号是可配置的，不一定是18080

2024-10-16 09:36 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/SimpleFileServer.java
> +  public static String PREFIX_UPLOAD = "/files/upload";
这个不要放在files下吧？因为/files里存放着zeppelin下载文件的文件，有一套自己的自动清理逻辑，如果upload文件夹也放在这下面，可能会被清理掉，可以看看另起一个文件夹

2024-10-17 07:14 UTC, liuxtq commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +  private static final String DEFAULT_FILE_UPLOAD_DIR = "/opt/module/zeppelin/uploads";
建议上传文件路径不暴露给用户，为服务器安全考虑。

2024-10-17 07:30 UTC, liuxtq commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +  private static final String DEFAULT_FILE_UPLOAD_DIR = "/opt/module/zeppelin/uploads";
1. 考虑到服务器安全问题，建议上传文件路径不开放给用户设置。
2. 由于存在非Linux部署环境，此处路径会改成相对路径。

2024-10-17 07:35 UTC, liuxtq commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +  private static final String DEFAULT_FILE_UPLOAD_DIR = "/opt/module/zeppelin/uploads";
1. 考虑到服务器安全问题，建议上传文件路径不开放给用户设置。
2. 由于存在非Linux部署环境，此处路径会改成相对路径。

2024-10-17 08:09 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +  private static final String DEFAULT_FILE_UPLOAD_DIR = "/opt/module/zeppelin/uploads";
对，不应该暴露给用户，可以改成相对路径，就放在zeppelin文件夹下。
如果方便的话可以把下载文件的存放路径也改成不暴露的相对路径。

2024-11-21 16:32 UTC, Yihao-Xu commented
调整一下format，其他没什么问题

2024-11-22 06:40 UTC, merged