基本完成network展示，调用命令>graph.network激活
IGinX-THU/zeppelin-interpreter pull request #23
Opened 2024-12-27 03:26 UTC by ChihuaYing

2024-12-31 02:24 UTC, Yihao-Xu requested changes

2024-12-31 02:24 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +      BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
bufferreader是否需要关闭？

2024-12-31 02:24 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +        IginxInterpreter8.class.getClassLoader().getResourceAsStream(htmlTemplate)) {
这里建议使用this.class，而不是IginxInterpreter8.class，因为我们还有个IginxInterpreter13，也同步使用这套代码

2024-12-31 02:24 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +      int depth = tree.traverseToHighchartsTreeNodes(tree.getRoot(), nodeList);
这个depth好像没用到？

2024-12-31 02:24 UTC, Yihao-Xu commented on v8/src/main/resources/static/vis/network.html
> +            // const allNodes = [{"depth":0,"id":"rootId","name":"","parent":"undefined"},{"depth":1,"id":"rootId.多维度数据分析","name":"多维度数据分析","parent":"rootId"},{"depth":1,"id":"rootId.国家海洋信息中心","name"
这个文件是示例吗？如果是的话建议文件名改一下。
这个文件是怎么生成的？具体生成逻辑好像没看到，是在这个pr中吗？

2024-12-31 02:24 UTC, Yihao-Xu commented on v8/src/main/resources/static/vis/network.html
> +<html lang="en">
network的展示结果能不能截一个图放在PR说明里？

2025-01-02 02:17 UTC, ChihuaYing commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +      BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
try-with-resources 形式会自动关闭

2025-01-02 02:21 UTC, ChihuaYing commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +        IginxInterpreter8.class.getClassLoader().getResourceAsStream(htmlTemplate)) {
已经修改为this.getClass()

2025-01-02 02:22 UTC, ChihuaYing commented on v8/src/main/java/org/apache/zeppelin/iginx/IginxInterpreter8.java
> +      int depth = tree.traverseToHighchartsTreeNodes(tree.getRoot(), nodeList);
已去除

2025-01-02 02:26 UTC, ChihuaYing commented on v8/src/main/resources/static/vis/network.html
> +            // const allNodes = [{"depth":0,"id":"rootId","name":"","parent":"undefined"},{"depth":1,"id":"rootId.多维度数据分析","name":"多维度数据分析","parent":"rootId"},{"depth":1,"id":"rootId.国家海洋信息中心","name"
这个文件可以视作一个html模板，这个Html会嵌入到zeppelin中。生成方式是读入html字节流，然后进行字符串替换。与“buildTreeForShowColumns”方法实现的方式是一模一样的，直接复用的它的代码。逻辑在这个pr中，大致为：try (InputStream inputStream =
        this.getClass().getClassLoader().getResourceAsStream(htmlTemplate)) {
      BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
      StringBuilder content = new StringBuilder();
      String line;
      while ((line = reader.readLine()) != null) {
        content.append(line).append("\n");
      }
      String html =
          content
              .toString()
              .replace("PARAGRAPH_ID", paragraphId)
              .replace("NODE_LIST", jsonString)
              .replace("GET_RELATION", String.valueOf(getRelation));
      return html;
    } catch ( ) {

    }

2025-01-02 02:33 UTC, ChihuaYing commented
1. 只展示网状结构，不聚合，也不分析特殊关系：>graph.network show columns;
<img width="919" alt="1735784822577" src="https://github.com/user-attachments/assets/f78ae012-9c7d-4c88-953c-b48d0354cb6c" />
2. 展示网络关系，且聚合并分析特殊关系（利用embedding）：>graph.network select KMeansMerge(*) from (show columns);其中KMeansMerge是自己实现的一个udf，用于聚合以及获取embedding
<img width="909" alt="1735784822586" src="https://github.com/user-attachments/assets/58969c10-6fa2-4963-b854-9b490bb19785" />
KMeansMerge的目前实现如下：
[KMeansMerge.zip](https://github.com/user-attachments/files/18287341/KMeansMerge.zip)
注册为udf的sql为：
CREATE FUNCTION UDSF "KMeansMerge" FROM "UDFKMeansMerge" IN "[path]//KMeansMerge.py";

2025-01-02 02:33 UTC, ChihuaYing commented on v8/src/main/resources/static/vis/network.html
> +<html lang="en">
已添加一个commet

2025-01-06 08:06 UTC, Yihao-Xu commented
把那个kmeans的udf文件传到v8/src/main/resources里吧

2025-01-06 08:24 UTC, merged