实现启动zeppelin时，检测文件服务的端口是否被占用，若已被占用则kill掉
IGinX-THU/zeppelin-interpreter pull request #24
Opened 2024-12-27 08:03 UTC by ChihuaYing

2024-12-31 02:07 UTC, Yihao-Xu requested changes

2024-12-31 02:07 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/SimpleFileServer.java
> +        killProcessOnWindows(port);
有没有条件实现以下在linux上的killProcess？

2024-12-31 02:07 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/SimpleFileServer.java
> +      BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
reader在结束时是否需要close？

2024-12-31 02:07 UTC, Yihao-Xu commented on v8/src/main/java/org/apache/zeppelin/iginx/SimpleFileServer.java
> +          break;
这里似乎是找到第一个pid就退出循环，有没有考虑过下面这种情况？我在我的电脑上执行了一下这个命令，一次找到了3个进程
![image](https://github.com/user-attachments/assets/0c4fe3f0-37be-4edb-a55e-570fcb94e6c3)

2025-01-02 02:48 UTC, ChihuaYing commented on v8/src/main/java/org/apache/zeppelin/iginx/SimpleFileServer.java
> +        killProcessOnWindows(port);
暂时没有诶，目前都是在windows环境测试的，原本的逻辑也只写了windows的

2025-01-02 02:59 UTC, ChihuaYing commented on v8/src/main/java/org/apache/zeppelin/iginx/SimpleFileServer.java
> +          break;
已修改逻辑为获取所有PID，并全都kill掉

2025-01-02 03:00 UTC, ChihuaYing commented on v8/src/main/java/org/apache/zeppelin/iginx/SimpleFileServer.java
> +      BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
已修改为使用try-with-resources，会自动关闭reader

2025-01-06 07:57 UTC, merged